### ISSUE TITLE
Slicing inconsistency with ndarrays

### ISSUE THREAD

**Issue by mz3-andrey** [v923z/micropython-ulab#128]
Was doing slicing on ulab version 0.26 and noticed something
I create a list with:
`test = [x for x in range(10)]`
and do a slice to give every third value:
`test[0::3]`
This returns as expected:
`[0, 3, 6, 9]`
However when doing the same slice to the equivalent ndarray i get a different result:
`np.array(test, dtype=np.int8)[0::3]`
returns
`[0, 3, 6]`
Doing both in python 3.6 with lists and np.ndarray returns the expected result [0, 3, 6, 9]
Am I missing something?
Thanks!

**Comment by mz3-andrey** [comment]
Sorry just noticed #50, any hints on updating an openmv's firmware to include the most recent version?
Thanks.

**Comment by v923z** [comment]
You can take a look at https://github.com/v923z/micropython-ulab/issues/124, where we discussed at length, how you can compile `openmv` with `ulab`. I also modified my side of the code, so that Ibrahim could easily include it on the `openmv` side. You should raise an issue over there.

**Comment by mz3-andrey** [comment]
Great! Thank you so much for your support.
