### ISSUE TITLE
Array operations not commutative

### ISSUE THREAD

**Issue by mz3-andrey** [v923z/micropython-ulab#131]
Very small thing, but I thought I might mention it.
I just noticed that `np.ones(3) * 3` works, but `3 * np.ones(3)` doesn't. Same goes for other operations.
I assume this is to do with micropython but I'm not sure.

**Comment by v923z** [comment]
> Very small thing, but I thought I might mention it.
> I just noticed that `np.ones(3) * 3` works, but `3 * np.ones(3)` doesn't. Same goes for other operations.
> I assume this is to do with micropython but I'm not sure.

Exactly. This is a relatively recent change in `micropython` itself. I think it was implemented sometime around January, or perhaps even later. `openmv` is based on v.1.9.4, which is more than two years old now. If you want commutative operators, you would have to convince Ibrahim to get the required code from upstream `micropython`.
