### ISSUE TITLE
ndarray.asbytearray() is gone?

### ISSUE THREAD

**Issue by mdaeron** [v923z/micropython-ulab#164]
I tried old code that used to run fine with one of the first versions of `ulab`. After upgarding to `ulab` v.0.54.0, i get the following error: `AttributeError: 'ndarray' object has no attribute 'asbytearray'`. Is the `asbytearray()` method gone, or was it just moved somewhere else?

**Comment by v923z** [comment]
It was removed, because `ndarray`s support the buffer protocol now, so it is not required. Here is a great example: https://learn.adafruit.com/ulab-crunch-numbers-fast-with-circuitpython/fft-example-waterfall-spectrum-analyzer

**Comment by mdaeron** [comment]
OK, thanks.
