### ISSUE TITLE
Implement `numpy.array.round()`

### ISSUE THREAD

**Issue by mdaeron** [v923z/micropython-ulab#168]
It would be useful to have an efficient way to round a `ndarray`, equivalent to `numpy.array.round()`, either returning a new rounded `ndarray` or rounding the original `ndarray` in place.

**Comment by v923z** [comment]
Is https://micropython-ulab.readthedocs.io/en/latest/ulab.html#around not what you need?

**Comment by mdaeron** [comment]
Duh. Yes, it is. I searched `round` in [readthedocs](https://micropython-ulab.readthedocs.io/en/latest/index.html) and it did not return that function. Thanks.

**Comment by v923z** [comment]
@mdaeron 
> Duh. Yes, it is. 

No problem.

> I searched `round` in [readthedocs](https://micropython-ulab.readthedocs.io/en/latest/index.html) and it did not return that function.

`numpy` itself is a bit ambiguous: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.round.html
