### ISSUE TITLE
Singular Matrix criteria is not correct (det, inv)

### ISSUE THREAD

**Issue by DeqingSun** [v923z/micropython-ulab#173]
Hi, today I tried to do some perspective transformation, but ulab told me this matrix is singular. And no surprise, det of such matrix (N=4) is 0.

![Screen Shot 2020-08-21 at 11 02 52 PM](https://user-images.githubusercontent.com/1385273/90947313-da320480-e402-11ea-89ea-5d323fe79696.png)

I guess this triggered by:

https://github.com/v923z/micropython-ulab/blob/bbe39d9e41af5adb0292537777ea376813a6f7c8/code/linalg/linalg.c#L161
meanwhile linalg_invert_matrix uses similar code.

So I tried following code in colab and numpy:

```
m = np.array([[0,1], [1,0]])
print(np.linalg.det(m))
print(linalg.inv(m))
```
I got
```
-1.0
[[0. 1.]
 [1. 0.]]
```
But ulab gave me 0 and an Singular error.

**Comment by v923z** [comment]
Thanks for taking action on this, I really appreciate it! The PR looks OK.
