### ISSUE TITLE
Feature request: adding equivalent of numpy.median()

### ISSUE THREAD

**Issue by mouryarahul** [v923z/micropython-ulab#189]
We already have some of the basic Statistical functions, e.g., `mean, std`, ..., I think adding `median` equivalent to [numpy.median](https://numpy.org/doc/stable/reference/generated/numpy.median.html) will be useful in many applications.

**Comment by v923z** [comment]
The `median` assumes that your data are already ordered along the axis. However, it is doable. But where would it be useful?

**Comment by mouryarahul** [comment]
Well, we already have `numerical.sort`, so implementing `median` shouldn't take much. Like `mean`,  `median` is also used in many instances.

**Comment by v923z** [comment]
@mouryarahul I believe, this issue is resolved.
