### ISSUE TITLE
labelling in linalg:eig example is reversed

### ISSUE THREAD

**Issue by fbtoc** [v923z/micropython-ulab#202]
In the eig example in the linalg module, x should be labelled eigenvalues and y eigenvectors.  Right now they are reversed.

**Comment by v923z** [comment]
You mean this https://micropython-ulab.readthedocs.io/en/latest/ulab-linalg.html#eig, don't you?

**Comment by v923z** [comment]
@fbtoc Thanks for pointing out the error! When cleaning up the docs, I also found a small bug int the code itself, so your comment was doubly useful.
