### ISSUE TITLE
ulab assumes that floats are boxed: MICROPY_OBJ_REPR_A or B

### ISSUE THREAD

**Issue by dhalbert** [v923z/micropython-ulab#24]
ulab is assuming that MicroPython is built with `MICROPY_OBJ_REPR_A` or `MICROPY_OBJ_REPR_B`, which store floats as boxed objects instead of as immediate values like smallints. In the code below, the float object is assumed to be boxed:

https://github.com/v923z/micropython-ulab/blob/81acfc7da8cb83dc7db018411c6fb97c82fdb7de/code/ulab.c#L29-L34

**Comment by v923z** [comment]
Since that is simply a version number, we can definitely change that. What do you suggest? A string, or integers as version major/minor? We could also define `__version__` as an attribute, and hook a function into it, and then we can return whatever we need.

**Comment by dhalbert** [comment]
Oops, just answered the same question here: https://github.com/v923z/micropython-ulab/issues/21#issuecomment-570822569

>I would suggest making the version a string, not a float, to have control over the formatting. E.g., is it "1.10" or "1.1"? And if one wanted to use semver-style, x.x.x, then it can't be a float.

**Comment by v923z** [comment]
@dhalbert Since this issue has been address somewhere else, I am closing it now.
