### ISSUE TITLE
Add numpy.isinf() & numpy.isfinite()

### ISSUE THREAD

**Issue by CallumJHays** [v923z/micropython-ulab#274]
`np.isinf` https://numpy.org/doc/stable/reference/generated/numpy.isinf.html

`np.isfinite` https://numpy.org/doc/stable/reference/generated/numpy.isinf.html

**Comment by v923z** [comment]
These two functions should be added to https://github.com/v923z/micropython-ulab/blob/master/code/compare/compare.c

**Comment by v923z** [comment]
@CallumJHays Cal, would https://github.com/v923z/micropython-ulab/tree/isinf do? I have also added some documentation here: https://github.com/v923z/micropython-ulab/blob/isinf/docs/manual/source/numpy-functions.rst. 

It would be really great, if you could add some tests in https://github.com/v923z/micropython-ulab/tree/isinf/tests. If you drop your test script under `tests/numpy`, and run the `build.sh` script in the root, that should automatically produce the expected results. Let me know if you need help with that.

**Comment by CallumJHays** [comment]
@v923z thanks! I was just about to get onto these. I'll try to get them done tomorrow
