### ISSUE TITLE
Add numpy ndarray alias?

### ISSUE THREAD

**Issue by CallumJHays** [v923z/micropython-ulab#275]
Often in my code I check for numpy-arrays via:
```python
if isinstance(x, np.ndarray): ...
```
Because in numpy, `np.array` isn't a class - it's an additional constructor function. `ndarray` is the class.

This is easy to patch in python code but I'm wondering if there'd be merit to exposing `ndarray` as an alias to `ulab.array`?

**Comment by v923z** [comment]
Am I correct that you want to define a new class, `ndarray`, and attach all `array` properties and methods to it?

**Comment by CallumJHays** [comment]
No, I essentially just want `ndarray = array`

**Comment by v923z** [comment]
Would then 
```c
{ MP_OBJ_NEW_QSTR(MP_QSTR_ndarray), (mp_obj_t)&ulab_ndarray_type },
```
do, right after 
https://github.com/v923z/micropython-ulab/blob/9484e846a36bc32253252feca6320c22a56a0839/code/numpy/numpy.c#L49?

**Comment by CallumJHays** [comment]
I suppose so? 😅 I'm still not that familiar with the C side of things

**Comment by v923z** [comment]
Actually, I think the solution is in your first comment, which I sort of overlooked. 

> Because in `numpy`, `np.array` isn't a class - it's an additional constructor function. `ndarray` is the class.

At the moment, `ulab.numpy.array` is an `ndarray` class. So, I think the solution is to change 

```c
{ MP_OBJ_NEW_QSTR(MP_QSTR_array), (mp_obj_t)&ulab_ndarray_type }, 
```
to 
```c
{ MP_OBJ_NEW_QSTR(MP_QSTR_ndarray), (mp_obj_t)&ulab_ndarray_type }, 
```
and then bind `array` to the constructor, i.e., `ndarray_make_new`. Do you want to take a stab at it, or should I fix it?

**Comment by CallumJHays** [comment]
I'll give it a go, looks like a good intro for me into the C code

**Comment by v923z** [comment]
The PR looks OK, thanks a lot!

**Comment by v923z** [comment]
The issue should be resolved by https://github.com/v923z/micropython-ulab/pull/280.
