### ISSUE TITLE
Add array.any() and array.all()

### ISSUE THREAD

**Issue by CallumJHays** [v923z/micropython-ulab#276]
`array.any()` https://numpy.org/doc/stable/reference/generated/numpy.ndarray.any.html

`array.all()` https://numpy.org/doc/stable/reference/generated/numpy.ndarray.all.html

**Comment by v923z** [comment]
Do you want to have `ndarray.any`, or `numpy.any`? Even if the code has to be implemented only once, any new binding adds to the code size.

**Comment by CallumJHays** [comment]
I would prefer `ndarray.any`, but it's actually just occurred to me that I can use python's `any()` and `all()` on ndarray instead for my purposes (my data is quite small, and I have no need for the `axis` arg).

Given the code size / compatibility dilemma in general, do you think it's worth implementing small features like this (even if they are behind an `#ifdef`)? Should a line be drawn?

**Comment by v923z** [comment]
> Given the code size / compatibility dilemma in general, do you think it's worth implementing small features like this (even if they are behind an `#ifdef`)? Should a line be drawn?

No, I don't think so. As long as it is customisable, it should be fine. We might have to add more documentation in the `ulab.h` header file itself, but that is OK. 

As far as compatibility is concerned, we have tried to stick with `numpy`'s convention in the past. This doesn't mean that all features, keywords etc. must be implemented, but that `ulab` code should run in `CPython`. The sole exception is the Fourier transform. Implementing all operators for complexes would definitely increase the firmware size considerably.

**Comment by v923z** [comment]
These two functions should be added to https://github.com/v923z/micropython-ulab/blob/master/code/compare/compare.c

**Comment by v923z** [comment]
@CallumJHays Cal, do you think you could add test scripts? The PR is here: https://github.com/v923z/micropython-ulab/pull/309

**Comment by CallumJHays** [comment]
@v923z ok I'll try to get it and #305 done this afternoon

**Comment by v923z** [comment]
https://github.com/v923z/micropython-ulab/pull/348 should close the issue.
