### ISSUE TITLE
ulab.numpy.array objects .shape not complete compatible numpy.array objects .shape

### ISSUE THREAD

**Issue by water5** [v923z/micropython-ulab#294]
ulab.numpy.array objects .shape -> <bound_method>
ulab.numpy.array objects .shape() -> <class 'tuple'>

numpy.array objects .shape -> <class 'tuple'>

**Comment by v923z** [comment]
The problem is that, as far as I know, defining properties is not implemented in `micropython`, so `.shape()` is really just a workaround. I will try to mount an effort, and get my PR concerning this issue accepted in `micropython` proper.

**Comment by jgpeiro** [comment]
But micropython DOES support properties, right?( I wanted to show you a repo that I remember about how to implement them in C...but its yours too!) [https://github.com/v923z/micropython-usermod/blob/master/snippets/properties/properties.c](url)

**Comment by v923z** [comment]
@jgpeiro The repo that you link to discusses a simple case, but here we would need something more complex: https://github.com/micropython/micropython/pull/5648

**Comment by water5** [comment]
Properties implemented.
