### ISSUE TITLE
[FEATURE REQUEST] backport `byteswap`

### ISSUE THREAD

**Issue by v923z** [v923z/micropython-ulab#336]
@dhalbert, @jepler Do you want me to backport this function? Here is the broader context: https://github.com/v923z/micropython-ulab/issues/306

**Comment by jepler** [comment]
If the original requestor of the feature was using CircuitPython, then probably yes.  Otherwise, not necessarily.

**Comment by v923z** [comment]
> If the original requestor of the feature was using CircuitPython

No, he wasn't. However, you are guaranteed to run into the endianness problem, if you try to pipe data from a peripheral device into a numerical array. On the other hand, at one point `circuitpython` is also going to switch to the `master` branch, so if you say that this is not a burning issue for you, I am not going to complain.

**Comment by v923z** [comment]
Closing the issue.  A new issue should be opened, if the functionality is required in `circuitpython`.
