### ISSUE TITLE
[Question] How to update ulab code with CircuitPython build?

### ISSUE THREAD

**Issue by water5** [v923z/micropython-ulab#373]
In CircuitPython, ulab included by default, but the ulab source code not enough update, I can't find ulab relate folder in 
[https://github.com/adafruit/circuitpython/tree/main/shared-bindings](https://github.com/adafruit/circuitpython/tree/main/shared-bindings), 
and I try to include independent ulab directory via:
`make BOARD=itsybitsy_m4_express USER_C_MODULES=../../../micropython-ulab all`, return error below:

> Use make V=1, make V=2 or set BUILD_VERBOSE similarly in your environment to increase build verbosity.
>
> Including User C Module from ../../../micropython-ulab/code
> QSTR updated
> {}
> ../../../micropython-ulab/code/scipy/optimize/optimize.c: In function 'optimize_fmin':
> ../../../micropython-ulab/code/scipy/optimize/optimize.c:156:24: error: comparing floating-point with '==' or '!=' is unsafe [-Werror=float-equal]
>   156 |     mp_float_t x1 = x0 != MICROPY_FLOAT_CONST(0.0) ? (MICROPY_FLOAT_CONST(1.0) + OPTIMIZE_NONZDELTA) * x0 : OPTIMIZE_ZDELTA;
> cc1: all warnings being treated as errors
> make: *** [../../py/mkrules.mk:55: build-itsybitsy_m4_express/code/scipy/optimize/optimize.o] Error 1

How should I update the ulab source code to latest for CircuitPython build?

**Comment by v923z** [comment]
@water5 Have you looked at https://github.com/v923z/micropython-ulab/blob/master/build-cp.sh? That will compile the unix port, but you could take that as a starting point.

**Comment by v923z** [comment]
@water5 Another thought: does 

```c
    mp_float_t x1 = x0 > MICROPY_FLOAT_C_FUN(fabs)(OPTIMIZE_EPS) ? (MICROPY_FLOAT_CONST(1.0) + OPTIMIZE_NONZDELTA) * x0 : OPTIMIZE_ZDELTA;
```
fix the issue?

```

**Comment by v923z** [comment]
@jepler Jeff, do you have any comments? I mean, `x1 == 0.0` is clear wrong, but I wonder, why it doesn't fail in the CI.

**Comment by water5** [comment]
I'm not ensure use `make BOARD=itsybitsy_m4_express USER_C_MODULES=../../../micropython-ulab all` is right way for CircuitPython build, 
because use `make BOARD=itsybitsy_m4_express` will generate firmware included ulab also, what location of the ulab source code in CircuitPython repository?

**Comment by v923z** [comment]
@water5 If you run the build script that I linked to above, it will clone `circuitpython` into the right place. First you have to clone `ulab`, and then run https://github.com/v923z/micropython-ulab/blob/master/build-cp.sh. Once you have the `unix` port, you can navigate into `circuitpython`, and find the port that you want to compile for. 

But you might get better help on the `circuitpython` github page. I am really not so knowledgeable about `circuitpython` issues.

**Comment by dhalbert** [comment]
All you have to do in CircuitPython is to make sure `CIRCUITPY_ULAB = 1`. Our build system will take care of everything else.

If you want to try a newer version of `ulab`, then move the commit for the submodule forward. You shouldn't need any extra command-line arguments (if I'm understanding what you're trying to do).

**Comment by dhalbert** [comment]
> what location of the ulab source code in CircuitPython repository?

`circuitpython/extmod/ulab`.

**Comment by v923z** [comment]
@water5 Could you, please check out `ulab` again, and try to compile it? I made an attempt at fixing the issue in https://github.com/v923z/micropython-ulab/pull/374.

**Comment by water5** [comment]
@v923z Refer :

> dhalbert: If you want to try a newer version of ulab, then move the commit for the submodule forward. You shouldn't > need any extra command-line arguments.

I just use wrong method to include `ulab` to build CircuitPython, I build it again use `make BOARD=mini_sam_m4 USER_C_MODULES=../../../micropython-ulab all` still currently (I'm not skill in use github), receive error below:

> Use make V=1, make V=2 or set BUILD_VERBOSE similarly in your environment to increase build verbosity.
> Including User C Module from ../../../micropython-ulab/code
> QSTR updated
> FREEZE ../../frozen/Adafruit_CircuitPython_DotStar
> {}
> ../../../micropython-ulab/code/scipy/signal/signal.c: In function 'signal_sosfilt':
> ../../../micropython-ulab/code/scipy/signal/signal.c:118:26: error: comparing floating-point with '==' or '!=' is unsafe [-Werror=float-equal]
>   118 |             if(coeffs[3] != MICROPY_FLOAT_CONST(1.0)) {
>       |                           #^~
> cc1: all warnings being treated as errors
> make: *** [../../py/mkrules.mk:55: build-mini_sam_m4/code/scipy/signal/signal.o] Error 1

I build CircuitPython via `make BOARD=mini_sam_m4` to use CircuitPython repository currently /extmod/ulab, is use : [https://github.com/v923z/micropython-ulab/tree/ef65415b5503ae71cc0a9064197f2e3fa5365d74](https://github.com/v923z/micropython-ulab/tree/ef65415b5503ae71cc0a9064197f2e3fa5365d74)
compile pass, 
see: [https://github.com/adafruit/circuitpython/tree/main/extmod](https://github.com/adafruit/circuitpython/tree/main/extmod)

**Comment by water5** [comment]
> If you want to try a newer version of `ulab`, then move the commit for the submodule forward.

How to do that (I'm not skill in use github)?

**Comment by v923z** [comment]
> @v923z Refer :
> 
> > dhalbert: If you want to try a newer version of ulab, then move the commit for the submodule forward. You shouldn't > need any extra command-line arguments.
> 
> I just use wrong method to include `ulab` to build CircuitPython, I build it again use `make BOARD=mini_sam_m4 USER_C_MODULES=../../../micropython-ulab all` still currently (I'm not skill in use github), receive error below:

I am no expert, but based on @dhalbert's comments, I assume that all you have to do is set `CIRCUITPY_ULAB=1` in one of the `mpconfigport.mk` files. E.g., there is one in `circuitpython/ports/atmel-samd`. (I believe that is what you would need for your port.). You don't have to pass `USER_C_MODULES=...` on the command line, just run `make` with the BOARD argument.

**Comment by dhalbert** [comment]
You do not need `USER_C_MODULES=../../../micropython-ulab all`, just `make BOARD=mini_sam_m4` is sufficient.

>If you want to try a newer version of ulab, then move the commit for the submodule forward

What is it exactly that you want in `ulab`. We are at version 2.6.0 + a few more commits. If you want the absolute latest:
```sh
$ cd circuitpyton/extmod/ulab
$ git checkout master
$ git pull
```
Then do a `make BOARD=mini_sam_m4 clean` and `make BOARD=mini_sam_m4`.

**Comment by water5** [comment]
Thanks, switch to latest `ulab` refer dhalber comment, and build CircuitPython again use `make BOARD=mini_sam_m4`,
build pass.
It's not a `ulab` issue? and it's not "do not need `USER_C_MODULES=../../../micropython-ulab all`", it can't use `USER_C_MODULES=../../../micropython-ulab all` when build `ulab` into CircuitPython, it will be cause some error, though I can't figure out the reason now, but should be update the instruction of `ulab` for CircuitPython. :)

**Comment by water5** [comment]
Is it should withdraw [https://github.com/v923z/micropython-ulab/pull/374#issue-623678541](https://github.com/v923z/micropython-ulab/pull/374#issue-623678541)?

**Comment by v923z** [comment]
> but should be update the instruction of `ulab` for CircuitPython. :)

I have added a section on `circuitpython` here: https://github.com/v923z/micropython-ulab/pull/375

**Comment by v923z** [comment]
This is resolved in https://github.com/v923z/micropython-ulab/pull/375, so closing now.
