### ISSUE TITLE
platform support?

### ISSUE THREAD

**Issue by erwincoumans** [v923z/micropython-ulab#4]
Is this generic C code that could easily build and run on linux, mac, windows?
Or does it only work on microcontrollers? (which ones?)

**Comment by v923z** [comment]
This is generic C code. In fact, most of the testing I do on a PC, using the unix port, which you can easily compile: https://micropython-usermod.readthedocs.io/en/latest/usermods_05.html#compiling-our-module

**Comment by erwincoumans** [comment]
great, thanks!
