### ISSUE TITLE
[BUG] numpy.any unexpected error

### ISSUE THREAD

**Issue by wired8** [v923z/micropython-ulab#459]
**Describe the bug**

numpy.any not working as expected.

NOTE:  I am using complex2 branch.

**To Reproduce**
```python
>>> numpy.any(np.array([0.003535534, 0.007071068]) >= 1)
(nil)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: _
```

**Comment by v923z** [comment]
This is fixed in https://github.com/v923z/micropython-ulab/pull/460
