### ISSUE TITLE
[BUG] np.diag

### ISSUE THREAD

**Issue by wired8** [v923z/micropython-ulab#502]
**Describe the bug**
Latest build (master)

Getting different results from ulab implementation of np.diag vs python numpy.diag.

**To Reproduce**

```python
a = np.array([1.0])
print(np.diag(a, k=-1))
>>> array([1.0], dtype=float64)
```

**Expected behavior**
```python
a = np.array([1.0])
print(np.diag(a, k=-1))
>>> array([[0. 0.] [1. 0.]], dtype=float64)
```

**Comment by v923z** [comment]
@wired8 Thanks, I will look into this.

**Comment by v923z** [comment]
@wired8 Phil, could you, please, check out https://github.com/v923z/micropython-ulab/pull/503, and test it?

**Comment by wired8** [comment]
Testing now.

**Comment by wired8** [comment]
Passed!  :+1:

**Comment by v923z** [comment]
@wired8 Thanks!
