### ISSUE TITLE
RP2 Firmware

### ISSUE THREAD

**Issue by Nmsngym** [v923z/micropython-ulab#510]
I cannot compile the firmware in my board, RP2040 Raspberry Pi Pico. I strictly do the steps, but the modules aren't recognized.

**Comment by v923z** [comment]
> I cannot compile the firmware in my board, RP2040 Raspberry Pi Pico. I strictly do the steps, but the modules aren't recognized.

If you cannot compile the firmware, how do you know that the modules are not recognised? 
Also, there is pre-compiled firmware for the Raspberry pi here: https://github.com/v923z/micropython-builder/releases

**Comment by Nmsngym** [comment]
Thank you so much for this.

**Comment by v923z** [comment]
I don't think this issue has to stay open.
