### ISSUE TITLE
Instructions for adding ulab to Lego Spike Prime

### ISSUE THREAD

**Issue by nw0428** [v923z/micropython-ulab#523]
I am trying to add ulab to Lego's spike prime product. This should be possible because it uses an [STM32F413](https://www.st.com/en/microcontrollers-microprocessors/stm32f413-423.html). Is it possible to compile and add ulab without flashing the entire system?

**Comment by v923z** [comment]
No, I don't think so. `ulab` is tightly integrated into the `micropython` firmware. It is really not like `python` on a PC, where you can install arbitrary libraries after the fact. I know that there are plans for making `micropython` more modular in this regard, but I have no idea, where those plans stand. 

But why is compilation and flashing a problem?

**Comment by v923z** [comment]
Since there hasn't been any traffic on this thread for a while, and since this is not really a `ulab` issue, closing now.
