### ISSUE TITLE
[FEATURE REQUEST] allow where to take a single argument

### ISSUE THREAD

**Issue by tejalbarnwal** [v923z/micropython-ulab#527]
**Describe the solution you'd like**
The `np.where()` implemented for `ulab` necessitates the requirement for 3 arguments, whereas `np.where()` in numpy also works with the only condition provided in the argument, where it works as `array_name.nonzero()` and returns the indices of those nonzero elements.
https://numpy.org/doc/stable/reference/generated/numpy.where.html

It could be great if this could be added.
#302

**Comment by v923z** [comment]
But this also works:

```python
>>> from ulab import numpy as np
>>> a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
>>> a > 3
array([[False, False, False],
       [True, True, True],
       [True, True, True]], dtype=bool)
```
After that, you simply have to iterate through the columns. 

To be honest, I am not sure I understand the example in https://numpy.org/doc/stable/reference/generated/numpy.nonzero.html#numpy.nonzero. How is 
```python
array([[False, False, False],
       [True, True, True],
       [True, True, True]], dtype=bool)
```
turned into 
```python
(array([1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2]))?
```

**Comment by tejalbarnwal** [comment]
the result 
```python
(array([1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2]))
```
says that there are non-zero values at 
```
(1,0), (1,1), (1,2), (2,0), (2,1) and (2,2)
```

**Comment by v923z** [comment]
> @v923z the result
> 
> ```python
> (array([1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2]))
> ```
> 
> says that there are non-zero values at
> 
> ```
> (1,0), (1,1), (1,2), (2,0), (2,1) and (2,2)
> ```
> 
> The first element of these tuples belong to the first array and likewise for the other one! 

Thanks for the clarification! 

> 
> Can this feature be implemented?

I can try to add this tonight, at least for the Boolean case. Can you help with the test scripts? https://github.com/v923z/micropython-ulab/#testing

**Comment by tejalbarnwal** [comment]
> I can try to add this tonight, at least for the Boolean case. Can you help with the test scripts? https://github.com/v923z/micropython-ulab/#testing

Thank you so much! Sure, I will be glad if I could contribute to this! 

> EDIT: However, I would add this as nonzero, instead of a special case of where, because it would be easier to switch off the function, if not needed.

Yeah, that works

**Comment by v923z** [comment]
@tejalbarnwal Could you, please, check out https://github.com/v923z/micropython-ulab/pull/540? The CI fails for whatever reason (I don't have time to fix that today), but I could compile the code locally, and the following works:

```python
>>> try:
>>>    from ulab import numpy as np
>>> except:
>>>    import numpy as np
>>>
>>> a = np.array(range(16)).reshape((4,4))
>>> print(a)
>>> print(a < 8)
>>> print(np.nonzero(a < 8))

array([[0.0, 1.0, 2.0, 3.0],
       [4.0, 5.0, 6.0, 7.0],
       [8.0, 9.0, 10.0, 11.0],
       [12.0, 13.0, 14.0, 15.0]], dtype=float64)
array([[True, True, True, True],
       [True, True, True, True],
       [False, False, False, False],
       [False, False, False, False]], dtype=bool)
(array([0, 0, 0, 0, 1, 1, 1, 1], dtype=uint16), array([0, 1, 2, 3, 0, 1, 2, 3], dtype=uint16))
```
I can continue to work on this tomorrow, but since you are ahead of me in time, I wanted to release whatever I had at the moment. 

I could, in principle, implement the same thing for non-Boolean arrays, but that comes with an overhead, because you have to compare unknown types to zero, and I am not sure, whether the convenience is worth the flash space. 

You can always take the longer route, and simply convert whatever condition you have to a Boolean array as demonstrated above. The binary operators already take care of the type conversion. I could, perhaps, call the binary operators internally. I am not sure at the moment, I'll look at it later.

**Comment by v923z** [comment]
@tejalbarnwal I have fixed the CI issue, so you should be able to clone the repository, and compile the code.

**Comment by v923z** [comment]
@tejalbarnwal `nonzero` should now behave as in `numpy`. Could you, please, check, whether it really does what it is supposed to do, so that we can merge it into master? Thanks!

**Comment by tejalbarnwal** [comment]
Hey, I apologize for the late reply. As I tried to compile the repository locally on ubuntu 20.04, I came across error with compilation. I have updated the `build.sh` file according to the new compilation process required for micropyhton. This can be found [here](https://github.com/v923z/micropython-ulab/pull/542)

**Comment by v923z** [comment]
If you check out https://github.com/v923z/micropython-ulab/pull/540 (just the `nonzero` branch), then you should be able to compile the code just by running `build.sh`.

**Comment by v923z** [comment]
Also note that https://github.com/v923z/micropython-ulab/pull/540/commits/c193e7f73b6720c770414235596c717345ca29f2 implements `nonzero` for the full gamut of `dtype`s, not only Booleans.

**Comment by tejalbarnwal** [comment]
> @tejalbarnwal nonzero should now behave as in numpy. Could you, please, check, whether it really does what it is supposed to do, so that we can merge it into master? Thanks!

sure, it exactly does what I want!

**Comment by v923z** [comment]
OK, thanks for the feedback! Do you think you could help with test scripts in the near future? I can hold this off for a couple of days.

**Comment by tejalbarnwal** [comment]
yup, am doing it right now

**Comment by v923z** [comment]
Yes, that is correct. The `.out` file will be generated, whenever there is no `py.exp` file in the folder, where the test script is, or when the results of the test script differ from the content of `.py.exp`. So, you simply have to move the `.out` file to `.py.exp`, after you inspected the results.

**Comment by tejalbarnwal** [comment]
Hey, sorry for asking such silly doubt.
I can't find any `.out` file generated directly, its only `out.npy` when I run `./build.sh` with the new snippet in `ulab/tests/2d/numpy` folder. Also, the result in `out.npy` doesn't seem to update every time I run `./build.sh`

**Comment by v923z** [comment]
No, I think the test script might be broken. I haven't noticed it before. I don't want to fix that in this round, so I would ask you to simply pipe the output of the test into the `.py.exp` file for now like so:

```bash
./micropython/ports/unix/micropython-2 ./tests/2d/numpy/nonzero.py > ./tests/2d/numpy/nonzero.py.exp
```

If you re-run `build.sh` at that point, the report should show that the test for `nonzero` passed. Thanks!

**Comment by v923z** [comment]
@tejalbarnwal I have fixed the issue with the missing test output file after all: https://github.com/v923z/micropython-ulab/pull/540/commits/e5b8a6f3d80f24bc7b22e7e92abb828ea5e47e94 
You should be able to simply run `build.sh`, and that should produce `some_test.py.out` file in the root directory. If you are satisfied with the output, you can move it to the test folder, under the name `some_test.py.exp`.

**Comment by v923z** [comment]
> Also, the result in `out.npy` doesn't seem to update every time I run `./build.sh`

That file is actually the result of the `load_save.py` test, and you can ignore it.

**Comment by tejalbarnwal** [comment]
Hey, I created a PR to add the test script https://github.com/v923z/micropython-ulab/pull/544

**Comment by tejalbarnwal** [comment]
Also, because am working with `OpenMV` using `ulab` on it. I tried to update the git submodule included in [OpenMV](https://github.com/openmv/openmv) by switching to the nonzero branch. 
The firmware doesn't build and gives an error related to ` undefined reference to io_load_obj, io_loadtxt_obj, io_save_obj, io_savetxt_obj`
The case is that this error is caused by `openmv/src/build/micropython/modules/ulab/code/numpy/numpy.o`

I am attaching the screenshot if it gives more information about the same.
![image](https://user-images.githubusercontent.com/64950661/181817846-c4457931-7ce3-4892-920d-e70286885c1f.png)
Am not sure where am I supposed to modify to get this fixed. Am I missing something?

**Comment by v923z** [comment]
No, I don't think you are missing anything. `openmv` is using an older version of `micropython`, I don't know, whether that is the problem.

Can you link it without those functions? Simply set `ULAB_NUMPY_HAS_LOADTXT`, and `ULAB_NUMPY_HAS_SAVE` to zero: https://github.com/v923z/micropython-ulab/blob/master/code/ulab.h. As far as I remember, `openmv` is very tight with space, so it might be that your firmware is just too big. 

If you can link without those two functions, we could try to find out why it fails.

**Comment by tejalbarnwal** [comment]
Hey, I commented out references to `ULAB_NUMPY_HAS_LOADTXT` , `ULAB_NUMPY_HAS_LOAD` , `ULAB_NUMPY_HAS_SAVE` and `ULAB_NUMPY_HAS_SAVETXT` and linked the `ulab` submodule to my forked repository and it worked like a charm!
Thank you sooo much!!

**Comment by v923z** [comment]
Closed by https://github.com/v923z/micropython-ulab/pull/540, and https://github.com/v923z/micropython-ulab/pull/544.
