### ISSUE TITLE
[BUG]Can't boot on esp32c3 on micropython v1.91

### ISSUE THREAD

**Issue by coinight** [v923z/micropython-ulab#530]
I had tried to make the firmware with ulab several times.But none is working.Mpy can be boot without ulab,but when i added USER_C_MODULES = ./ulab/code/micropython.cmake to the makefile,the compile succeed but boot failed.So i wonder how to solve the problem.
Thanks.
![1](https://user-images.githubusercontent.com/32589807/176797705-37eeae26-04c5-408e-a562-e69734a5d791.png)

**Comment by coinight** [comment]
the version of espidf is v4.4

**Comment by v923z** [comment]
@coinight I don't have this board, but my first guess would be that the firmware might be too big for this particular chip. What you could do is reduce the number of dimensions, and switch off as many functions/features as possible: https://micropython-ulab.readthedocs.io/en/latest/ulab-intro.html#customising-the-firmware. That should significantly reduce the firmware size. If you strip everything, and leave only the FFT, `ulab` adds around 5 kB.

**Comment by coinight** [comment]
Thanks a lot.I don't know this issue before.I will try your advise recently. Thanks again :)

**Comment by v923z** [comment]
@coinight Can we close the issue, or do you still have difficulties with the compilation?
