### ISSUE TITLE
Uploading RP2 firmware.uf2 seemingly does not work

### ISSUE THREAD

**Issue by MicahHaack** [v923z/micropython-ulab#543]
After following the rp2 compilation steps and generating the firmware.uf2 file, upon uploading the file to my PICO, no available COM port is found.

One exception to the steps for rp2 compilation was needing to update submodules with this command:
git -submodule update --init

After that update command the firmware claimed to have built properly. However, uploading the firmware does not allow me to access the PICO at all.

**Comment by v923z** [comment]
I think we should try to understand, whether the issue has anything to do with `ulab`. What happens, if you compile `micropython` without any user modules? Can you access the PICO then? Are the steps listed in this repository faulty, or the same happens, if you follow the instructions of https://github.com/micropython/micropython/tree/master/ports/rp2?

**Comment by MicahHaack** [comment]
I just compiled only with micropython using the steps provided above, and after uploading the uf2 file I can see the COM port again.

**Comment by v923z** [comment]
Can it be that with `ulab`, the firmware is just too big? You can reduce the number of dimensions, and take out functions to reduce the size: https://micropython-ulab.readthedocs.io/en/latest/ulab-intro.html#customising-the-firmware

**Comment by MicahHaack** [comment]
I went to recompile the ulab version to check the size again and for some reason I think it works now. Shrug.
![image](https://user-images.githubusercontent.com/44842363/181622845-4574a571-4ec1-4d59-8883-6965f92cb23a.png)
I am able to talk to my PICO and import the ulab modules. I am unsure why it didn't work before.

**Comment by v923z** [comment]
It could be that didn't run `make clean` or something.

**Comment by v923z** [comment]
@MicahHaack It has just occurred to me that you can actually download the firmware from here: https://github.com/v923z/micropython-builder/releases
