### ISSUE TITLE
[BUG] Compilation fails after latest micropython commit

### ISSUE THREAD

**Issue by uraich** [v923z/micropython-ulab#547]
**Describe the bug**

Latest changes in micropython break ulab (using latest version)

**To Reproduce**
Try to recompile latest micropython version with ulab included

**Additional context**

![image](https://user-images.githubusercontent.com/1673533/191000627-c1b17979-11a8-49be-b8ed-c2b6c984d77c.png)

**Comment by jimmo** [comment]
@uraich sorry you're a step ahead of me. I was going to send a PR to ulab tomorrow to fix this.

Did you see the build troubleshooting error that now gets emitted at the end of the compile?

**Comment by jimmo** [comment]
Raised https://github.com/v923z/micropython-ulab/issues/548 with more info.

**Comment by uraich** [comment]
Well, I am not always this fast! Thanks for the prompt answer. I can wait a few days until ulab will work with the new version of micropython.

**Comment by v923z** [comment]
@uraich It seems to that you run into difficulties only with the `optimize` sub-module. You can undefine those functions, if you don't need them, and I believe, after that you should be able to compile.

**Comment by uraich** [comment]
@jimmo said he will create a PR to correct those problems. I can easily wait a few days. I have an ESP32 with a recent micropython and ulab that works just fine. 
Thank you very much for your quick answer.

**Comment by v923z** [comment]
Closed via https://github.com/v923z/micropython-ulab/pull/549
