### ISSUE TITLE
[FEATURE REQUEST] numpy.hypot

### ISSUE THREAD

**Issue by mnai01** [v923z/micropython-ulab#562]
https://numpy.org/doc/stable/reference/generated/numpy.hypot.html

**Comment by v923z** [comment]
Is this not just a shortcut for `qrt(x1**2 + x2**2)`? If so, wouldn't it better to add this as a snippet? I try to steer clear of just aliases, given that they add to the firmware, while they don't introduce new functionality.

**Comment by mnai01** [comment]
Yes, you're correct I found this out after the post. `sqrt(x1**2 + x2**2)`  should work fine, I just have yet to test it.
