### ISSUE TITLE
[FEATURE REQUEST] add numpy.correlate

### ISSUE THREAD

**Issue by v923z** [v923z/micropython-ulab#600]
As described in https://github.com/v923z/micropython-ulab/discussions/597, add the C implementation of https://numpy.org/doc/stable/reference/generated/numpy.correlate.html

@hamza-712

**Comment by v923z** [comment]
@hamza-712 Actually, thinking of this, you can already calculate the correlation of two arrays by flipping one of the arrayas, and calling `convolve`. Would that not work for you?

**Comment by hamza-712** [comment]
Thanks, I've implemented just like you said.

**Comment by v923z** [comment]
@hamza-712 Can we close the issue, then?

**Comment by hamza-712** [comment]
@v923z  thanks, yes you may close it.
