### ISSUE TITLE
[FEATURE REQUEST] support reshape(-1) for ndarrays

### ISSUE THREAD

**Issue by Derfies** [v923z/micropython-ulab#608]
Super handy to be able to flatten an array to 1 dimension in vanilla numpy, eg:
```
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.reshape(-1))
-> [1 2 3 4 5 6]
```
whereas this raises
`TypeError: shape must be a tuple`
in ulab.

Using a tuple, ie arr.reshape((-1,)) gives the same issue unfortunately.

**Comment by Derfies** [comment]
Ah. After a little more perusing I take it that .flatten is the way to go here?

**Comment by v923z** [comment]
If you want to, we could add `.reshape(-1)` as an alias for `.flatten`. Are they really the same?

**Comment by Derfies** [comment]
I've used numpy a fair bit but I don't consider myself an authority on the matter. Perhaps leave it as is rather than confused the next boffin who knows the nuance between these two methods!

**Comment by v923z** [comment]
One element in the tuple can actually be -1: https://numpy.org/doc/stable/reference/generated/numpy.reshape.html

**Comment by v923z** [comment]
@Derfies `numpy` is not quite pedantic, and while the documentation states that the unknown dimension length should be -1, it is actually not checked. In any case, https://github.com/v923z/micropython-ulab/pull/612 implements this feature.

**Comment by Derfies** [comment]
Thank you!!
