### ISSUE TITLE
[FEATURE REQUEST] New stable release/tag please ?

### ISSUE THREAD

**Issue by iabdalkader** [v923z/micropython-ulab#609]
Just requesting a new release/tag to track, since the major change in the mp type definition broke the old release 🙏🏼

**Comment by v923z** [comment]
Here you go: https://github.com/v923z/micropython-ulab/releases/tag/6.0.12. 
Would you be interested in adding your build script here: https://github.com/v923z/micropython-builder? People would then always have cutting-edge firmware.

**Comment by iabdalkader** [comment]
Thank you!

> Would you be interested in adding your build script

 Yes I'll try to add a script to build the latest board.

**Comment by v923z** [comment]
> Yes I'll try to add a script to build the latest board.

If you want to add multiple boards, I would be happy to host them, too.
