### ISSUE TITLE
[BUG] element wise "and logic" & operator doesnt work. 

### ISSUE THREAD

**Issue by hamza-712** [v923z/micropython-ulab#641]
**Describe the bug**
I'm trying to do element-wise and operation. Currently its not working same as normal numpy.
 `ulab` version '6.0.7-2D-c'

**Normal python**
``` python
import numpy as np
arr1 = np.array([True, False, True])
arr2 = np.array([False, True, True])



print(arr1 & arr2)
```
**Result** # returns [False False  True]

**Micropython ulab**
```python
from ulab import numpy as np
arr1 = np.array([True, False, True])
arr2 = np.array([False, True, True])

print(arr1 and arr2) # gives Incorrect answer array([0.0, 1.0, 1.0], dtype=float32)
print(arr1 & arr2) # gives TypeError: unsupported types for __and__: 'ndarray', 'ndarray'
np.logical_and(arr1, arr2) # AttributeError: 'module' object has no attribute 'logical_and'

```

**Expected behavior**
Element wise and logic is not working. 
[False False  True]

**Comment by v923z** [comment]
This was added in version 6.4: https://github.com/v923z/micropython-ulab/blob/master/docs/ulab-change-log.md

**Comment by hamza-712** [comment]
thanks
