### ISSUE TITLE
[BUG]`np.delete`,if pass the second positional argument empty list `[]`,the program crashed.

### ISSUE THREAD

**Issue by hiltay** [v923z/micropython-ulab#652]
Give the `ulab` version :newest

```python
>>> a
array([[1.0, 2.0, 3.0],
       [4.0, 5.0, 6.0]], dtype=float32)
>>> np.delete(a,[],axis=1)
```

**To Reproduce**
when using `np.delete`, if pass the second positional argument empty list `[]`,the program crashed.

**Comment by v923z** [comment]
Thanks for the report!

**Comment by hiltay** [comment]
I create a pr to fix that: https://github.com/v923z/micropython-ulab/pull/653

**Comment by hiltay** [comment]
I think this bug is fixed! Close the issue now:)
