### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ValergooD** [v923z/micropython-ulab#656]
**Describe the bug**
A clear and concise description of what the bug is. Give the `ulab` version
Error message after build 
Makefile:18: The PICO* boards have been renamed to RPI_PICO* Makefile:20: *** Invalid BOARD specified: boards/PICO_W.  Stop. Makefile:18: The PICO* boards have been renamed to RPI_PICO* Makefile:20: *** Invalid BOARD specified: boards/PICO_W.  Stop.
For fix need use this in file "rp2w.sh" change "BOARD=PICO_W" to  "BOARD=RPI_PICO_W"
```python
import ulab
print(ulab.__version__)
```

**To Reproduce**
Describe the steps to reproduce the behavior.

**Expected behavior**

**Additional context**
Add any other context that might help to locate the root of the problem.

**Comment by v923z** [comment]
Thanks for the bug report!

**Comment by v923z** [comment]
Fixed, closing now.
