### ISSUE TITLE
[BUG] ReadTheDocs link in README.md is years out of date

### ISSUE THREAD

**Issue by dhalbert** [v923z/micropython-ulab#668]
**Describe the bug**
The ReadTheDocs "badge" that is linked in `README.md` points to a forked repo that has not been updated in years:
https://github.com/v923z/micropython-ulab/blob/65c941a8059afe1cfd6f4c2b15d0ade798dc24f2/README.md?plain=1#L3

I think you want it to point to https://micropython-ulab.readthedocs.io/en/latest/index.html ?

**Comment by v923z** [comment]
Indeed, thanks for pointing this out! Fixed in https://github.com/v923z/micropython-ulab/commit/e40a667e3c22251fba36a4b7a38d9f75635210f7.
