### ISSUE TITLE
[FEATURE REQUEST] M55 Vectorization

### ISSUE THREAD

**Issue by kwagyeman** [v923z/micropython-ulab#691]
@v923z - Hi we'd like to run by you adding support for vectorized operations using the M55 to ulab. We've already started this process for our vision library and could use this for ulab. Could we meet to discuss this?

Thanks,

**Comment by v923z** [comment]
Yes, certainly. Thanks for bringing this up! Let's try to set up a meeting over e-mail!

**Comment by kwagyeman** [comment]
I messaged you via our slack.

**Comment by kwagyeman** [comment]
Sent an email too.
