### ISSUE TITLE
Minor inconsistency in accessed the one element from ndarray

### ISSUE THREAD

**Issue by mouryarahul** [v923z/micropython-ulab#74]
I'm not sure if this is intentional:
`>>> a = np.array([[1,2,3],[4,5,6],[7,8,9]])`
`>>> a[1,1]`
`array([5.0], dtype=float)`
`>>> a[1][1]`
`5.0`
why in the first case we get an array while in second case a numeric value? In numpy, both result into a numeric value rather in array container.

**Comment by v923z** [comment]
This shouldn't be so. I thought I had sorted this out, but this is obviously not the case. Thanks!

**Comment by v923z** [comment]
Duplicate: https://github.com/v923z/micropython-ulab/issues/17
