### ISSUE TITLE
Certain inconsistency in numerical.argsort function 

### ISSUE THREAD

**Issue by mouryarahul** [v923z/micropython-ulab#89]
@v923z I'm not sure if this is intentional?

```
MicroPython v1.12-337-g312c69949 on 2020-04-06; PYBD-SF6W with STM32F767IIK
Type "help()" for more information.
>>> import ulab as np
>>> np.__version__
'0.41.0'
>>> a = np.array([[4,5,6],[1,2,3],[7,8,9]])
>>> np.numerical.argsort(a, axis=0)
array([[1, 1, 1],
         [0, 0, 0],
         [2, 2, 2]], dtype=uint16)
>>> a
array([[4.0, 5.0, 6.0],
         [1.0, 2.0, 3.0],
         [7.0, 8.0, 9.0]], dtype=float)
>>> np.numerical.argsort(a, axis=None)
array([3, 4, 5, 0, 1, 2, 6, 7, 8], dtype=uint16)
>>> a
array([4.0, 5.0, 6.0, 1.0, 2.0, 3.0, 7.0, 8.0, 9.0], dtype=float)
```
whereas the documentation of `ULAB` mentions: "Since during the sorting, only the indices are shuffled, argsort does not modify the input array...". The original array is flattened when `axis=None`. The `Numpy` behaves as the documentation of `ULAB` mentions.

**Comment by v923z** [comment]
> @v923z I'm not sure if this is intentional?

No it wasn't, thanks for reporting the issue. I think https://github.com/v923z/micropython-ulab/pull/90 should fix it.
