### ISSUE TITLE
Bug in ulab.linalg.dot function

### ISSUE THREAD

**Issue by mouryarahul** [v923z/micropython-ulab#94]
@v923z `linalg.dot` seems to have a certain bug:
```
MicroPython v1.12-368-gbd63c26dd on 2020-04-13; PYBD-SF6W with STM32F767IIK
Type "help()" for more information.
>>> ulab.__version__
'0.41.2'

>>> A
array([[1.0, 2.0],
         [3.0, 4.0]], dtype=float)
>>> B
array([[1.0, 2.0, 3.0, 4.0],
         [5.0, 6.0, 7.0, 8.0]], dtype=float)
>>> ulab.linalg.dot(A,B)
array([[11.0, 23.0, 14.0, 30.0],
         [17.0, 37.0, 20.0, 44.0]], dtype=float)
```
whereas the correct result from Numpy is:
```
np.dot(A,B)
array([[11, 14, 17, 20],
       [23, 30, 37, 44]])
```
Seems that it has something to do with way the elements are stored in the array!
Can you reproduce the same at your end?

**Comment by v923z** [comment]
Indeed, there was in indexing error in the function implementation. I have fixed it in https://github.com/v923z/micropython-ulab/pull/96.
