### ISSUE TITLE
Feature request: clip()

### ISSUE THREAD

**Issue by PaintYourDragon** [v923z/micropython-ulab#97]
Feature request: an equivalent to numpy’s clip() function. Sure, same operation can be done in a couple lines of Python, but the speed of occurring entirely in ulab space would be a big plus. Thanks.

**Comment by v923z** [comment]
Noted. Give be a couple of days!

**Comment by v923z** [comment]
@PaintYourDragon @ladyada see https://github.com/v923z/micropython-ulab/pull/106 (it is actually more than what was requested).
